# Fichier de secrets de l’application Streamlit.
# Ce fichier est utilisé par Streamlit pour se connecter à Snowflake.

[snowflake]
account = "HABIXRB-QYB88421"
user = "Adam"
password = "Amoussaoui54444"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
